#!/bin/bash

#TYPE=DEBUG
TYPE=RELEASE

BASE_DIR=$HOME/opt/trilinos/src
INSTALL_DIR=$HOME/opt/trilinos/install

rm -rf CMake*

cmake \
-D CMAKE_BUILD_TYPE:STRING=$TYPE \
-D CMAKE_INSTALL_PREFIX:STRING=$INSTALL_DIR \
-D CMAKE_C_FLAGS:STRING="-DH5_HAVE_PARALLEL -DSHYLU_NODEBASKER" \
-D CMAKE_CXX_FLAGS:STRING="-DH5_HAVE_PARALLEL -DSHYLU_NODEBASKER" \
-D CMAKE_C_COMPILER=mpicc \
-D CMAKE_CXX_COMPILER=mpicxx \
-D CMAKE_Fortran_COMPILER=mpifort \
-D MPI_EXEC_MAX_NUMPROCS:STRING=8 \
-D CMAKE_CXX_STANDARD:STRING=17 \
-D BUILD_SHARED_LIBS:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_Fortran:BOOL=ON \
-D Trilinos_ENABLE_OpenMP:BOOL=OFF \
-D Trilinos_ENABLE_Kokkos:BOOL=ON \
-D Trilinos_ENABLE_Teuchos:BOOL=ON \
-D Trilinos_ENABLE_Epetra:BOOL=ON \
-D Trilinos_ENABLE_EpetraExt:BOOL=ON \
-D Trilinos_ENABLE_PyTrilinos:BOOL=OFF \
-D Trilinos_ENABLE_Xpetra:BOOL=ON \
-D Trilinos_ENABLE_Tpetra:BOOL=ON \
-D Trilinos_ENABLE_AztecOO:BOOL=OFF \
-D Trilinos_ENABLE_Belos:BOOL=ON \
-D Trilinos_ENABLE_Anasazi:BOOL=ON \
-D Trilinos_ENABLE_Amesos:BOOL=OFF \
-D Trilinos_ENABLE_Amesos2:BOOL=ON \
-D Trilinos_ENABLE_NOX:BOOL=ON \
-D NOX_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_Zoltan:BOOL=ON \
-D Zoltan_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_Zoltan2:BOOL=ON \
-D Trilinos_ENABLE_Ifpack2:BOOL=ON \
-D Trilinos_ENABLE_Thyra:BOOL=ON \
-D Thyra_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_ShyLU:BOOL=OFF \
-D Trilinos_ENABLE_ShyLU_DDFROSch:BOOL=ON \
-D Trilinos_ENABLE_Stratimikos:BOOL=ON \
-D Stratimikos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_MueLu:BOOL=OFF \
-D Trilinos_ENABLE_ML:BOOL=OFF \
-D Trilinos_ENABLE_Sacado:Bool=OFF \
-D Sacado_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_Panzer:BOOL=OFF \
-D Trilinos_ENABLE_Intrepid2:BOOL=OFF \
-D Trilinos_ENABLE_Shards:BOOL=OFF \
-D Trilinos_ENABLE_STK:BOOL=OFF \
-D Trilinos_ENABLE_Galeri:BOOL=ON \
-D Trilinos_ENABLE_Teko:BOOL=ON \
-D TPL_FIND_SHARED_LIBS:BOOL=ON \
-D TPL_ENABLE_DLlib:BOOL=OFF \
-D TPL_ENABLE_Pthread:BOOL=OFF \
-D TPL_ENABLE_MPI:BOOL=ON \
-D TPL_ENABLE_LAPACK:BOOL=ON \
-D TPL_ENABLE_BLAS:BOOL=ON \
-D TPL_ENABLE_Matio:BOOL=OFF \
-D TPL_ENABLE_METIS:BOOL=ON \
-D TPL_ENABLE_ParMETIS:BOOL=ON \
-D TPL_ENABLE_UMFPACK:BOOL=ON \
-D TPL_ENABLE_Boost:BOOL=ON \
-D TPL_ENABLE_HDF5:BOOL=ON \
-D Trilinos_EXTRA_LINK_FLAGS:STRING="" \
-D Trilinos_ENABLE_CONFIGURE_TIMING=ON \
-D Trilinos_ENABLE_PACKAGE_CONFIGURE_TIMING=ON \
$BASE_DIR
