#!/bin/bash

BUILD_TYPE=DEBUG # DEBUG, RELEASE

MPI_C_COMPILER=mpicc
MPI_CXX_COMPILER=mpicxx
MPI_FORTRAN_COMPILER=mpifort

BASE_FEDDLIB=$HOME/dev/feddlib

TRILINOS_DIR=$HOME/opt/trilinos/install
SOURCE_DIR=$BASE_FEDDLIB/src
INSTALL_DIR=$BASE_FEDDLIB/install
BUILD_DIR=$BASE_FEDDLIB/build

### Compiler flags
# Macros are set s.t. "#ifdef MACRO" can be used in the code.
MACROS="-D HAVE_EXPLICIT_INSTANTIATION -D FROSCH_Epetra64 -D WeUseTpetra -D NEW_PARMETIS -D NEW_METIS"
# FLAGS is always used
# FLAGS_RELEASE is used only if build type is RELEASE
# FLAGS_DEBUG is used only if build type is DEBUG
FLAGS="$MACROS -Wno-cpp" # -Wno-deprecated -Wno-sign-compare -Wno-unused-variable -fpermissive"
#FLAGS = "$MACROS"
FLAGS_RELEASE="-O3 -march=native"
#FLAGS_RELEASE=""
FLAGS_DEBUG="-O0 -ggdb -debug all -traceback -ftrapuv"
#FLAGS_DEBUG=""

rm -rf $BUILD_DIR/CMake*

cmake \
-D CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=True \
-D CMAKE_BUILD_TYPE:STRING=${BUILD_TYPE} \
-D CMAKE_C_COMPILER=$MPI_C_COMPILER \
-D CMAKE_CXX_COMPILER=$MPI_CXX_COMPILER \
-D CMAKE_Fortran_COMPILER=$MPI_FORTRAN_COMPILER \
-D CMAKE_INSTALL_PREFIX:STRING=$INSTALL_DIR \
-D CMAKE_C_FLAGS:STRING="$FLAGS" \
-D CMAKE_CXX_FLAGS:STRING="$FLAGS" \
-D CMAKE_C_FLAGS_RELEASE:STRING="$FLAGS_RELEASE" \
-D CMAKE_CXX_FLAGS_RELEASE:STRING="$FLAGS_RELEASE" \
-D CMAKE_C_FLAGS_DEBUG:STRING="$FLAGS_DEBUG" \
-D CMAKE_CXX_FLAGS_DEBUG:STRING="$FLAGS_DEBUG" \
-D CMAKE_CXX_STANDARD=17 \
-D MPI_EXEC_MAX_NUMPROCS:STRING=4 \
-D MPI_EXEC_PRE_NUMPROCS_FLAGS="--oversubscribe" \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
-D FEDDLib_ENABLE_ALL_PACKAGES:BOOL=ON \
-D FEDDLib_ENABLE_EXAMPLES:BOOL=ON \
-D FEDDLib_ENABLE_TESTS:BOOL=ON \
-D TPL_FIND_SHARED_LIBS:BOOL=OFF \
-D TPL_ENABLE_MPI:BOOL=ON \
-D TPL_ENABLE_Trilinos:BOOL=ON \
-D Trilinos_INCLUDE_DIRS:PATH=$TRILINOS_DIR/include \
-D Trilinos_LIBRARY_DIRS:PATH=$TRILINOS_DIR/lib \
-S ${SOURCE_DIR} -B ${BUILD_DIR}

# MPI_EXEC_MAX_NUMPROCS: Tests requiring more than the specified number of processes are excluded from CTest.

