TRIBITS_TPL_FIND_INCLUDE_DIRS_AND_LIBRARIES( HDF5
  REQUIRED_HEADERS hdf5.h H5FDmpio.h
  REQUIRED_LIBS_NAMES "hdf5"
)

SET(CMAKE_REQUIRED_INCLUDES ${TPL_HDF5_INCLUDE_DIRS})
SET(CMAKE_REQUIRED_LIBRARIES ${TPL_HDF5_LIBRARY_DIRS})

message (" HDF5 found! ")
