      double precision SMSDot,SMSKDelta,SMSDeltaPart,SMSSum
      double precision SMSMAX,SMSMIN

      include   'bdata.h'
      include   'pdata6.h'
      include   'cdata.h'
      include   'eldata.h'
      include   'iofile.h'
      include   'rdata.h' 
      include   'strnum.h'
      include   'hdata.h'
      include   'prstrs.h'
      include   'comblk.h'
      include   'sdata.h'
      include   'pointer.h'
      include   'counts.h'
      include   'tdata.h'

      include   'sensitivity.h'


      integer ID_IDataLength          
      integer ID_RDataLength          
      integer ID_IDataLast            
      integer ID_RDataLast            
      integer ID_LastIntCode                
      integer ID_Iteration            
      integer ID_TotalIteration       
      integer ID_LinearEstimate       
      integer ID_ErrorStatus          
      integer ID_MaterialState        
      integer ID_NoSensParameters     
      integer ID_ElementShape         
      integer ID_SensIndex            
      integer ID_OutputFile           
      integer ID_MissingSubroutine    
      integer ID_SubDivergence        
      integer ID_ElementState         
      integer ID_SensType                
      integer ID_SensTypeIndex                
      integer ID_NoNodes              
      integer ID_NoElements           
      integer ID_NoESpec              
      integer ID_dummy1          
      integer ID_Debug                
      integer ID_NoDimensions         
      integer ID_SymmetricTangent      
      integer ID_MinNoTmpData         
      integer ID_NoEquations          
      integer ID_DiagonalSign         
      integer ID_Task                 
      integer ID_NoSubIterations      
      integer ID_CurrentElement       
      integer ID_MaxPhysicalState     
      integer ID_ExtrapolationType    
      integer ID_TmpContents          
      integer ID_AssemblyNodeResidual 
      integer ID_NodeReordering       
      integer ID_SkipSolver           
      integer ID_NoNSpec              
      integer ID_SetSolver            
      integer ID_NoShapeParameters    
      integer ID_GeometricTangentMatrix  
      integer ID_DataMemory           
      integer ID_SolverMemory         
      integer ID_Solver               
      integer ID_ErrorElement         
      integer ID_SkipTangent          
      integer ID_SkipResidual         
      integer ID_SubIterationMode     
      integer ID_Solver1              
      integer ID_Solver2              
      integer ID_Solver3              
      integer ID_Solver4              
      integer ID_Solver5              
      integer ID_ContactProblem       
      integer ID_Contact1             
      integer ID_Contact2             
      integer ID_Contact3             
      integer ID_Contact4             
      integer ID_Contact5             
      integer ID_PostIteration        
      integer ID_DummyNodes           
      integer ID_PostIterationCall    
      integer ID_Step                 
      integer ID_DebugElement         
      integer ID_ZeroPivot            
      integer ID_GlobalIterationMode  
      integer ID_NoDiscreteEvents     
      integer ID_LineSearchUpdate  
      integer ID_NoBackStep        
      integer ID_SkipSubIteration  
      integer ID_HideIndeterminate
      integer ID_NoMessages
      integer ID_MaxMessages
      integer IData_Last              
      integer IData_Length   
  
      parameter(ID_RDataLength          =1)
      parameter(ID_IDataLast            =2)
      parameter(ID_RDataLast            =3)
      parameter(ID_LastIntCode          =4)
      parameter(ID_Iteration            =5)
      parameter(ID_TotalIteration       =6)
      parameter(ID_LinearEstimate       =7)
      parameter(ID_ErrorStatus          =8)
      parameter(ID_MaterialState        =9)
      parameter(ID_NoSensParameters     =10)
      parameter(ID_ElementShape         =11)
      parameter(ID_SensIndex            =12)
      parameter(ID_OutputFile           =13)
      parameter(ID_MissingSubroutine    =14)
      parameter(ID_SubDivergence        =15)
      parameter(ID_ElementState         =16)
      parameter(ID_SensType             =17)
      parameter(ID_SensTypeIndex        =18)
      parameter(ID_NoNodes              =19)
      parameter(ID_NoElements           =20)
      parameter(ID_NoESpec              =21)
      parameter(ID_dummy1               =22)
      parameter(ID_Debug                =23)
      parameter(ID_NoDimensions         =24)
      parameter(ID_SymmetricTangent     =25)
      parameter(ID_MinNoTmpData         =26)
      parameter(ID_NoEquations          =27)
      parameter(ID_DiagonalSign         =28)
      parameter(ID_Task                 =29)
      parameter(ID_NoSubIterations      =30)
      parameter(ID_CurrentElement       =31)
      parameter(ID_MaxPhysicalState     =32)
      parameter(ID_ExtrapolationType    =33)
      parameter(ID_TmpContents          =34)
      parameter(ID_AssemblyNodeResidual =35)
      parameter(ID_NodeReordering       =36)
      parameter(ID_SkipSolver           =37)
      parameter(ID_NoNSpec              =38)
      parameter(ID_SetSolver            =39)
      parameter(ID_NoShapeParameters    =40)
      parameter(ID_GeometricTangentMatrix  =41)
      parameter(ID_DataMemory           =42)
      parameter(ID_SolverMemory         =43)
      parameter(ID_Solver               =44)
      parameter(ID_ErrorElement         =45)
      parameter(ID_SkipTangent          =46)
      parameter(ID_SkipResidual         =47)
      parameter(ID_SubIterationMode     =48)
      parameter(ID_Solver1              =49)
      parameter(ID_Solver2              =50)
      parameter(ID_Solver3              =51)
      parameter(ID_Solver4              =52)
      parameter(ID_Solver5              =53)
      parameter(ID_ContactProblem       =54)
      parameter(ID_Contact1             =55)
      parameter(ID_Contact2             =56)
      parameter(ID_Contact3             =57)
      parameter(ID_Contact4             =58)
      parameter(ID_Contact5             =59)
      parameter(ID_PostIteration        =60)
      parameter(ID_DummyNodes           =61)
      parameter(ID_PostIterationCall    =62)
      parameter(ID_Step                 =63)
      parameter(ID_DebugElement         =64)
      parameter(ID_ZeroPivot            =65)
      parameter(ID_GlobalIterationMode  =66)
      parameter(ID_NoDiscreteEvents     =67)
      parameter(ID_LineSearchUpdate     =68)
      parameter(ID_NoBackStep           =69)
      parameter(ID_IDataLength          =70)
      parameter(ID_SkipSubIteration     =71)
      parameter(ID_HideIndeterminate    =72)
      parameter(ID_NoMessages           =73)
      parameter(ID_MaxMessages          =74)
      parameter(IData_Last              =74)
      parameter(IData_Length            =400)


      integer RD_Multiplier            
      integer RD_ResidualError         
      integer RD_IncrementError        
      integer RD_MFlops                
      integer RD_SubMFlops             
      integer RD_Time                  
      integer RD_TimeIncrement         
      integer RD_MultiplierIncrement   
      integer RD_SubIterationTolerance 
      integer RD_LineSearchStepLength  
      integer RD_PostMaxValue          
      integer RD_PostMinValue          
      integer RD_TotalEnergy           
      integer RD_PotentialEnergy       
      integer RD_KineticEnergy         
      integer RD_Solver1               
      integer RD_Solver2               
      integer RD_Solver3               
      integer RD_Solver4               
      integer RD_Solver5               
      integer RD_Contact1              
      integer RD_Contact2              
      integer RD_Contact3              
      integer RD_Contact4              
      integer RD_Contact5              
      integer RD_ContactSearchTolerance
      integer RD_MinX                  
      integer RD_MinY                  
      integer RD_MinZ                  
      integer RD_MaxX                  
      integer RD_MaxY                  
      integer RD_MaxZ                  
      integer RD_XYZRange              
      integer RD_KAndRTime
      integer RD_SolverTime            
      integer RData_Last                
      integer RData_Length             


      parameter(RD_ResidualError         =1)
      parameter(RD_IncrementError        =2)
      parameter(RD_MFlops                =3)
      parameter(RD_SubMFlops             =4)
      parameter(RD_Time                  =5)
      parameter(RD_TimeIncrement         =6)
      parameter(RD_MultiplierIncrement   =7)
      parameter(RD_SubIterationTolerance =8)
      parameter(RD_LineSearchStepLength  =9)
      parameter(RD_PostMaxValue          =10)
      parameter(RD_PostMinValue          =11)
      parameter(RD_TotalEnergy           =12)
      parameter(RD_PotentialEnergy       =13)
      parameter(RD_KineticEnergy         =14)
      parameter(RD_Solver1               =15)
      parameter(RD_Solver2               =16)
      parameter(RD_Solver3               =17)
      parameter(RD_Solver4               =18)
      parameter(RD_Solver5               =19)
      parameter(RD_Contact1              =20)
      parameter(RD_Contact2              =21)
      parameter(RD_Contact3              =22)
      parameter(RD_Contact4              =23)
      parameter(RD_Contact5              =24)
      parameter(RD_ContactSearchTolerance =25)
      parameter(RD_MinX                  =26)
      parameter(RD_MinY                  =27)
      parameter(RD_MinZ                  =28)
      parameter(RD_MaxX                  =29)
      parameter(RD_MaxY                  =30)
      parameter(RD_MaxZ                  =31)
      parameter(RD_XYZRange              =32)
      parameter(RD_KAndRTime             =33)
      parameter(RD_SolverTime            =34)
      parameter(RD_Multiplier            =35)
      parameter(RData_Last               =35) 
      parameter(RData_Length             =400)


      integer ERROR_NoError,ERROR_Warning,ERROR_StepCut,ERROR_Fatal
      parameter(ERROR_NoError=0,ERROR_Warning=1,
     # ERROR_StepCut=2,ERROR_Fatal=3)

      integer idata(IData_Length),ngpo,IntSwitch(100),ckiter
      double precision gp(4,100),rdata(RData_Length),DoubleSwitch(100)
      common/smscommon/gp,rdata,DoubleSwitch,idata,ngpo,
     # IntSwitch,ckiter
