#!/bin/bash
BUILD_TYPE=DEBUG

MPI_C_COMPILER=`which mpicc`
MPI_CXX_COMPILER=`which mpicxx`

TRILINOS_DIR=/.../Trilinos-install
SOURCE_DIR=/.../feddlib
MPI_LIB_DIR=/.../openmpi-3.1.5/lib
rm -rf CMake*
cmake \
	-D CMAKE_BUILD_TYPE:STRING=${BUILD_TYPE} \
	-D CMAKE_C_COMPILER:PATH=${MPI_C_COMPILER} \
	-D CMAKE_CXX_COMPILER:PATH=${MPI_CXX_COMPILER} \
	-D CMAKE_CXX_FLAGS:STRING="-D FROSCH_Epetra64 -D HAVE_EXPLICIT_INSTANTIATION -Wno-write-strings" \
	-D CMAKE_CXX_STANDARD_LIBRARIES:STRING="${MPI_LIB_DIR}/libmpi_mpifh.dylib -lgfortran" \
	-D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
	-D MPI_BIN_DIR="/.../openmpi-3.1.5/bin" \
    -D MPI_EXEC:FILEPATH="mpirun" \
    -D MPI_EXEC_PRE_NUMPROCS_FLAGS="--oversubscribe" \ #for OpenMPI versions >= 3
    -D MPI_EXEC_MAX_NUMPROCS="8" \
	-D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
	-D FEDDLib_ENABLE_ALL_PACKAGES:BOOL=ON \
	-D FEDDLib_ENABLE_TESTS:BOOL=ON \
	-D TPL_ENABLE_MPI:BOOL=ON \
	-D TPL_ENABLE_Trilinos:BOOL=ON \
	-D Trilinos_INCLUDE_DIRS:PATH=$TRILINOS_DIR/include \
	-D Trilinos_LIBRARY_DIRS:PATH=$TRILINOS_DIR/lib \
	${SOURCE_DIR}
