tribits_package_define_dependencies(
  LIB_REQUIRED_PACKAGES core
  LIB_OPTIONAL_PACKAGES
  TEST_REQUIRED_PACKAGES
  TEST_OPTIONAL_PACKAGES
  LIB_REQUIRED_TPLS MPI Trilinos
  LIB_OPTIONAL_TPLS
  TEST_REQUIRED_TPLS
  TEST_OPTIONAL_TPLS
)
