enable_language(C)
include(CheckFunctionExists)
check_function_exists(dlopen DLOPEN_IN_LIBC)

tribits_package_define_dependencies(
  LIB_REQUIRED_PACKAGES
  LIB_OPTIONAL_PACKAGES
  TEST_REQUIRED_PACKAGES
  TEST_OPTIONAL_PACKAGES
  LIB_OPTIONAL_TPLS AceGENInterface
  TEST_REQUIRED_TPLS
  TEST_OPTIONAL_TPLS
)

IF (UNIX AND NOT APPLE AND NOT DLOPEN_IN_LIBC)
  TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
    LIB_REQUIRED_TPLS MPI Trilinos HDF5 Z DL
  )
ELSE()
  TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
    LIB_REQUIRED_TPLS MPI Trilinos HDF5 Z
  )
ENDIF()
